import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../comps/header";
import Footer from "../comps/footer";
import { AuthProvider } from './profile/authenti';
import ScrollProvider from "../components/ScrollProvider"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sherlock Dong",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ScrollProvider>
            <Header />
            {/* ADD YOUR LEFT PADDING HERE */}
            {/* pl-8 gives a nice gap, pl-20 gives a massive asymmetrical gap */}
            <main className="min-h-screen pl-8 md:pl-16 overflow-x-hidden">
              {children}
            </main>
            <Footer />
          </ScrollProvider>
        </AuthProvider>
      </body>
    </html>
  );
}