import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"
import { AuthProvider } from './profile_arc/authenti';
import ScrollProvider from "../components/ScrollProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sherlock Dong",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en" suppressHydrationWarning>
      <Analytics />
      <body className={inter.className}>
        <main className="min-h-screen pl-8 md:pl-16 overflow-x-hidden">

          {children}
        </main>
      </body>
    </html>
  );
}